language: node_js
node_js:
  - "11.10.1" # lock to node 11.10.1 in travis due to https://github.com/facebook/jest/issues/8069
install:
  - npm i -g npm@5.8.0
  - npm ci
script:
  - npm run examples:lint
  - npm run examples:test
branches:
  only:
    - master
    - next
cache:
  directories:
    - "$HOME/.npm"
