name: Bundle Size

on: [pull_request]

permissions:
  contents: read

jobs:
  build:
    permissions:
      checks: write  # for preactjs/compressed-size-action to create and update the checks
      contents: read  # for actions/checkout to fetch code
      issues: write  # for preactjs/compressed-size-action to create comments
      pull-requests: write  # for preactjs/compressed-size-action to write a PR review
    name: Check compressed size
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2-beta
        with:
          fetch-depth: 1
      - uses: preactjs/compressed-size-action@v1
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
